# runs https://github.com/Joel-hanson/bandit-report-artifacts security routine

name: Bandit Security
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: Joel-hanson/bandit-report-artifacts@V1
