# runs https://github.com/Joel-hanson/bandit-report-artifacts security routine

name: Bandit Security
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Python security check using Bandit
      uses: Joel-hanson/bandit-report-artifacts@V1
      with:
        name: Security report
        path: output/security_report.txt
