# This workflow will zip pryno folder and create a release html for it
# ignores -m with 'cd skip' and 'release skip'

name: Create Release
on:
    push:
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        name: Release Pryno

        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'cd skip' // 'release skip')"

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Zip pryno/
              run: |
                zip -r pryno.zip pryno

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is auto provided by Actions
              with:
                tag_name: ${{ github.ref }} # get tag
                release_name: Release ${{ github.ref }}
                body:  ${{ github.event.head_commit.message }} # get commit message
                draft: false
                prerelease: false

            - name: Upload Release Asset
              id: upload-release-asset 
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the step above
                asset_path: ./pryno.zip
                asset_name: pryno.zip
                asset_content_type: application/zip
