# This workflow will send authenticated /reset POST requests to EC2 containers
# running the bot, triggering then the continuous deployment cicle
# runs on pushes tagged with 'v*' via git tags, ignores -m with 'cd skip'

name: Signal Deploy
on:
    push:
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
      runs-on: ubuntu-latest
      name: Update Vm
      if: "!contains(github.event.head_commit.message, 'cd skip')"

      steps:
       - name: Install curl
         run: |
            sudo apt install curl

       - name: Update ShaolinMataPorco
         run: |
          curl --header "Content-Type: application/json" --request POST --data '{"pwd":"kero10gostosasda19computacao"}' http://ec2-52-48-28-220.eu-west-1.compute.amazonaws.com/reset

       - name: Update Ellint
         run: |
          curl --header "Content-Type: application/json" --request POST --data '{"pwd":"kero10gostosasda19computacao"}' http://ec2-34-245-92-42.eu-west-1.compute.amazonaws.com/reset

       - name: Update Missio
         run: |
          curl --header "Content-Type: application/json" --request POST --data '{"pwd":"kero10gostosasda19computacao"}' http://ec2-3-250-4-255.eu-west-1.compute.amazonaws.com/reset

       - name: Update Shady
         run: |
          curl --header "Content-Type: application/json" --request POST --data '{"pwd":"kero10gostosasda19computacao"}' http://ec2-34-245-12-90.eu-west-1.compute.amazonaws.com/reset

       - name: Update Zuza
         run: |
          curl --header "Content-Type: application/json" --request POST --data '{"pwd":"kero10gostosasda19computacao"}' http://ec2-176-34-71-138.eu-west-1.compute.amazonaws.com/reset

       - name: Update QuanManagment
         run: |
          curl --header "Content-Type: application/json" --request POST --data '{"pwd":"kero10gostosasda19computacao"}' http://ec2-34-248-255-232.eu-west-1.compute.amazonaws.com/reset
